name = "Google Chrome"
vendor = "Google"
description = "Google Chrome is a web browser developed by Google. It was first released in 2008 for Microsoft Windows, built with free software components from Apple WebKit and Mozilla Firefox. Versions were later released for Linux, macOS, iOS, iPadOS, and also for Android, where it is the default browser. The browser is also the main component of ChromeOS, where it serves as the platform for web applications."
homepage = "https://www.google.com/chrome/"
categories = ["Network", "Web Browser"]
tags = ["Web Browser", "Google", "Chromium", "Chrome"]
